Repository boostcampwm-2024/web33-Nocta, pull requests merged in 2024-11, with the labels that each got.

#4 Feature/#003 환경 설정
  .github/ISSUE_TEMPLATE/bug-fix-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/request-template.md
  .github/ISSUE_TEMPLATE/🚨-bug-report-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  README.md
  client/.gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/tsconfig.tsbuildinfo
  client/vite.config.ts
  eslint.config.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  server/.gitignore
  server/README.md
  server/eslint.config.js
  server/nest-cli.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
  tsconfig.base.json
Labels: FE, BE, Build

#75 Feature/#005_Docker_이미지_빌드
  client/Dockerfile
  client/Dockerfile.dev
  client/package.json
  docker-compose.debug.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/Dockerfile.dev
  nginx/default.conf
  nginx/default.dev.conf
  server/Dockerfile
  server/Dockerfile.dev
Labels: Build

#76 Feature/#006_배포_자동화_구축
  .github/workflows/deploy.yml
Labels: Build

#79 Feature/#078 실시간 통신 및 db 환경 설정
  client/package.json
  pnpm-lock.yaml
  server/package.json
Labels: FE, BE, Build

#82 Feature/#081 eslint 에러안뜨는 버그 픽스
  .prettierrc
  .vscode/settings.json
  client/index.html
  client/src/App.tsx
  client/src/main.tsx
  client/vite.config.ts
Labels: Bug, P1

#84 Feature/#083 PR 템플릿 개요 삭제
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#88 Feature/#087 ESLint가 dist를 검사하는 문제 수정
  client/eslint.config.js
  eslint.config.js
  server/eslint.config.js
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
Labels: Bug, P1

#90 Feature/#085 Github Actions workflow 추가
  .github/workflows/auto_merge_approved_pr.yml
  .github/workflows/deploy.yml
  .github/workflows/lint_and_test.yml
Labels: Build

#91 Feature/#080 panda css 라이브러리 설정
  .prettierrc
  client/.gitignore
  client/eslint.config.js
  client/package.json
  client/panda.config.ts
  client/postcss.config.cjs
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/icons/plusIcon.svg
  client/src/assets/images/background.png
  client/src/assets/react.svg
  client/src/components/bottomNavigator/BottomNavigator.style.ts
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/button/IconButton.style.ts
  client/src/components/button/IconButton.tsx
  client/src/components/sidebar/MenuButton.style.ts
  client/src/components/sidebar/MenuButton.tsx
  client/src/components/sidebar/PageItem.style.ts
  client/src/components/sidebar/PageItem.tsx
  client/src/components/sidebar/Sidebar.style.ts
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/editor/Editor.tsx
  client/src/features/page/Page.style.ts
  client/src/features/page/Page.tsx
  client/src/features/page/components/PageControlButton.style.ts
  client/src/features/page/components/PageControlButton.tsx
  client/src/features/workSpace/WorkSpace.style.ts
  client/src/features/workSpace/WorkSpace.tsx
  client/src/index.css
  client/src/styles/global.ts
  client/src/styles/recipes/glassContainerRecipe.ts
  client/src/styles/tokens/color.ts
  client/src/styles/tokens/radii.ts
  client/src/styles/tokens/shadow.ts
  client/src/styles/tokens/spacing.ts
  client/src/styles/typography.ts
  client/tsconfig.json
  eslint.config.js
  pnpm-lock.yaml
Labels: FE, Feat, P1

#92 Feature/#085 auto_merge_approved_pr.yml 오류 수정
  .github/workflows/auto_merge_approved_pr.yml
Labels: Bug, Build

#93 Feature/#085 auto_merge_approved_pr.yml 오류 수정
  .github/workflows/auto_merge_approved_pr.yml
Labels: Bug, Build

#99 Feature/#098 nocta crdt 라이브러리 client, server가 접근 가능하도록 환경 구축
  .gitignore
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/LinkedList.ts
  @noctaCrdt/Node.ts
  @noctaCrdt/package.json
  @noctaCrdt/tsconfig.json
  client/package.json
  client/tsconfig.json
  client/vite.config.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  server/nest-cli.json
  server/package.json
  server/tsconfig.json
  server/webpack.config.js
Labels: Feat, Build

#95 Feature/#094 기초 마크다운 에디터 구현
  @noctaCrdt/dist/Crdt.d.ts
  @noctaCrdt/dist/Crdt.d.ts.map
  @noctaCrdt/dist/Crdt.js
  @noctaCrdt/dist/Crdt.js.map
  @noctaCrdt/dist/Interfaces.d.ts
  @noctaCrdt/dist/Interfaces.d.ts.map
  @noctaCrdt/dist/Interfaces.js
  @noctaCrdt/dist/Interfaces.js.map
  @noctaCrdt/dist/LinkedList.d.ts
  @noctaCrdt/dist/LinkedList.d.ts.map
  @noctaCrdt/dist/LinkedList.js
  @noctaCrdt/dist/LinkedList.js.map
  @noctaCrdt/dist/Node.d.ts
  @noctaCrdt/dist/Node.d.ts.map
  @noctaCrdt/dist/Node.js
  @noctaCrdt/dist/Node.js.map
  @noctaCrdt/dist/tsconfig.tsbuildinfo
  client/package.json
  client/src/components/block/Block.style.ts
  client/src/components/block/Block.tsx
  client/src/features/editor/Editor.style.ts
  client/src/features/editor/Editor.tsx
  client/src/features/page/Page.tsx
  client/src/features/page/components/PageControlButton/PageControlButton.style.ts
  client/src/features/page/components/PageControlButton/PageControlButton.tsx
  client/src/features/page/components/PageTitle/PageTitle.style.ts
  client/src/features/page/components/PageTitle/PageTitle.tsx
  client/src/hooks/useCaretManager.ts
  client/src/hooks/useMarkdownGrammer/handlers/arrow.ts
  client/src/hooks/useMarkdownGrammer/handlers/backSpace.ts
  client/src/hooks/useMarkdownGrammer/handlers/enter.ts
  client/src/hooks/useMarkdownGrammer/handlers/handlerProps.ts
  client/src/hooks/useMarkdownGrammer/handlers/space.ts
  client/src/hooks/useMarkdownGrammer/index.ts
  client/src/styles/typography.ts
  client/src/types/markdown.ts
  client/src/utils/blockNavigationUtils.ts
  client/src/utils/linkedLIstBlock.ts
  client/src/utils/markdownPatterns.ts
  client/tsconfig.json
  client/tsconfig.tsbuildinfo
  pnpm-lock.yaml
Labels: FE, Design, Build, P1

#105 Feature/#104 탭 브라우징 반응형 구현
  client/package.json
  client/src/components/sidebar/Sidebar.animation.ts
  client/src/components/sidebar/Sidebar.style.ts
  client/src/components/sidebar/Sidebar.tsx
  client/src/constants/size.ts
  client/src/features/page/hooks/usePage.ts
  client/src/stores/useSidebarStore.ts
  pnpm-lock.yaml
Labels: FE, Feat

#103 Feature/#097 베포 및 테스트용 MongoDB 구축
  .github/workflows/deploy.yml
  docker-compose.debug.yml
  docker-compose.yml
  pnpm-lock.yaml
  server/package.json
  server/src/app.module.spec.ts
  server/src/app.module.ts
Labels: BE, Build

#108 Feature/#107 클라이언트 빌드 에러 해결
  client/src/features/page/Page.tsx
  client/src/hooks/useMarkdownGrammer/handlers/backSpace.ts
Labels: Bug, FE

#111 Feature/#106 Docker에서 noctaCrdt, pandaCSS 경로를 인식하지 못하는 문제 수정
  @noctaCrdt/dist/Crdt.d.ts
  @noctaCrdt/dist/Crdt.d.ts.map
  @noctaCrdt/dist/Crdt.js
  @noctaCrdt/dist/Crdt.js.map
  @noctaCrdt/dist/Interfaces.d.ts
  @noctaCrdt/dist/Interfaces.d.ts.map
  @noctaCrdt/dist/Interfaces.js
  @noctaCrdt/dist/Interfaces.js.map
  @noctaCrdt/dist/LinkedList.d.ts
  @noctaCrdt/dist/LinkedList.d.ts.map
  @noctaCrdt/dist/LinkedList.js
  @noctaCrdt/dist/LinkedList.js.map
  @noctaCrdt/dist/Node.d.ts
  @noctaCrdt/dist/Node.d.ts.map
  @noctaCrdt/dist/Node.js
  @noctaCrdt/dist/Node.js.map
  @noctaCrdt/dist/tsconfig.tsbuildinfo
  client/Dockerfile
  client/panda.config.ts
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/page/Page.tsx
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/styles/tokens/color.ts
  client/src/styles/tokens/sizes.ts
  client/src/styles/tokens/spacing.ts
  client/tsconfig.json
  client/vite.config.ts
  pnpm-workspace.yaml
  server/Dockerfile
Labels: Bug, Build

#113 Feature/#097 MongoDB 테스트 환경 구축
  .github/workflows/deploy.yml
  .github/workflows/lint_and_test.yml
  .gitignore
  docker-compose.debug.yml
  docker-compose.yml
  pnpm-lock.yaml
  server/jest-mongodb-config.ts
  server/jest.config.ts
  server/package.json
  server/src/app.module.spec.ts
  server/src/app.module.ts
Labels: Bug, Build

#116 Feature/BE/#115 server socket.io로 mongo db연동
  .github/workflows/lint_and_unit_test.yml
  @noctaCrdt/package.json
  @noctaCrdt/tsconfig.json
  pnpm-workspace.yaml
  server/jest.config.ts
  server/package.json
  server/src/app.module.ts
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.module.ts
  server/src/crdt/crdt.service.ts
  server/src/schemas/document.schema.ts
  server/tsconfig.json
  server/webpack.config.js
Labels: BE, Feat

#118 Feature/#117 crdt 라이브러리 개선
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/LinkedList.ts
  @noctaCrdt/Page.ts
  @noctaCrdt/WorkSpace.ts
Labels: Refactor

#123 Feature/#121 crdt 라이브러리 db스키마로 개선
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/LinkedList.ts
  @noctaCrdt/Node.ts
  @noctaCrdt/NodeId.ts
  @noctaCrdt/Page.ts
  @noctaCrdt/WorkSpace.ts
Labels: Feat

#124 Feature/#122 mongo db block crdt연동
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.module.ts
  server/src/crdt/crdt.service.ts
  server/src/crdt/schemas/document.schema.ts
  server/src/schemas/document.schema.ts
  server/tsconfig.json
Labels: BE

#126 Feature/#119 모달 공통 컴포넌트 구현
  client/index.html
  client/src/components/button/textButton.style.ts
  client/src/components/button/textButton.tsx
  client/src/components/modal/modal.animation.ts
  client/src/components/modal/modal.style.ts
  client/src/components/modal/modal.tsx
  client/src/components/modal/useModal.ts
Labels: FE, Feat

#129 Feature/#127 탭 브라우징 피드백 반영
  client/package.json
  client/src/assets/icons/close.svg
  client/src/assets/icons/expand.svg
  client/src/assets/icons/minus.svg
  client/src/assets/images/background.png
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/modal/modal.animation.ts
  client/src/components/modal/modal.style.ts
  client/src/components/sidebar/MenuButton.style.ts
  client/src/components/sidebar/MenuButton.tsx
  client/src/components/sidebar/PageItem.style.ts
  client/src/components/sidebar/Sidebar.style.ts
  client/src/components/sidebar/Sidebar.tsx
  client/src/constants/page.ts
  client/src/features/page/Page.animation.ts
  client/src/features/page/Page.style.ts
  client/src/features/page/Page.tsx
  client/src/features/page/components/PageControlButton/PageControlButton.style.ts
  client/src/features/page/components/PageControlButton/PageControlButton.tsx
  client/src/features/page/components/PageTitle/PageTitle.style.ts
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/styles/global.ts
  client/tsconfig.json
  client/vite-env-override.d.ts
  client/vite.config.ts
  client/vite.env.d.ts
  pnpm-lock.yaml
Labels: FE, Feat

#128 Refactor/#120 클라이언트 crdt 라이브러리 적용
  client/src/components/block/Block.style.ts
  client/src/components/block/Block.tsx
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/components/block/IconBlock.tsx
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/editor/utils/markdownPatterns.ts
  client/src/hooks/useCaretManager.ts
  client/src/hooks/useMarkdownGrammer/handlers/arrow.ts
  client/src/hooks/useMarkdownGrammer/handlers/backSpace.ts
  client/src/hooks/useMarkdownGrammer/handlers/enter.ts
  client/src/hooks/useMarkdownGrammer/handlers/handlerProps.ts
  client/src/hooks/useMarkdownGrammer/handlers/space.ts
  client/src/hooks/useMarkdownGrammer/index.ts
  client/src/types/markdown.ts
  client/src/utils/blockNavigationUtils.ts
  client/src/utils/linkedLIstBlock.ts
  client/src/utils/markdownPatterns.ts
  client/tsconfig.tsbuildinfo
Labels: Bug, FE, Feat, P1

#132 Feature/#131 블록 드래그앤드랍 구현
  @noctaCrdt/LinkedList.ts
  client/package.json
  client/src/assets/icons/draggable.svg
  client/src/features/editor/Editor.style.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/IconBlock/ IconBlock.style.ts
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  client/src/features/editor/components/MenuBlock/MenuBlock.style.ts
  client/src/features/editor/components/MenuBlock/MenuBlock.tsx
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockDragAndDrop.ts
  client/tsconfig.tsbuildinfo
  pnpm-lock.yaml
Labels: FE, Feat, Build, P1

#135 Feature/#130 로그인 회원가입 ui 구현
  client/src/assets/icons/lock.svg
  client/src/assets/icons/mail.svg
  client/src/assets/icons/user.svg
  client/src/components/button/textButton.style.ts
  client/src/components/inputField/InputField.style.ts
  client/src/components/inputField/InputField.tsx
  client/src/components/modal/modal.style.ts
  client/src/components/sidebar/MenuButton.style.ts
  client/src/components/sidebar/MenuButton.tsx
  client/src/features/auth/AuthModal.style.ts
  client/src/features/auth/AuthModal.tsx
  client/src/styles/typography.ts
Labels: FE, Feat

#142 Feature/#136 HTTPS 접속을 위한 NginX 설정 변경
  docker-compose.yml
  nginx/Dockerfile
  nginx/default.conf
Labels: BE, Build

#134 Feature/#133 로티 애니메이션 추가
  client/package.json
  client/src/assets/lotties/errorAlert.json
  client/src/assets/lotties/loadingSpinner.json
  client/src/components/loading/LoadingSpinner.tsx
  pnpm-lock.yaml
Labels: Build

#144 Feature/#143 nanoid ESM버전 미응대 문제
  client/src/features/editor/components/IconBlock/IconBlock.style.ts
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  pnpm-lock.yaml
  server/package.json
Labels: Bug, Build

#145 Feature/#136 NginX HTTPS 관련 버그 수정
  .github/workflows/deploy.yml
  .github/workflows/lint_and_test.yml
  docker-compose.yml
Labels: Build

#146 Feature/#139 react query 세팅
  @noctaCrdt/Crdt.ts
  client/package.json
  client/src/apis/auth.ts
  client/src/features/auth/AuthModal.tsx
  client/src/main.tsx
  client/tsconfig.tsbuildinfo
  pnpm-lock.yaml
  server/src/app.module.spec.ts
  server/src/crdt/crdt.service.ts
  server/src/crdt/schemas/document.schema.ts
  server/src/main.ts
Labels: FE, Feat

#141 Feature/#137 workspace에 로티애니메이션 적용
  client/src/components/lotties/ErrorAlert.tsx
  client/src/components/lotties/LoadingSpinner.tsx
  client/src/components/modal/ErrorModal.style.ts
  client/src/components/modal/ErrorModal.tsx
  client/src/components/modal/modal.style.ts
  client/src/features/workSpace/WorkSpace.style.ts
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/components/IntroScreen.style.ts
  client/src/features/workSpace/components/IntroScreen.tsx
  client/src/features/workSpace/hooks/useWorkspaceInit.ts
Labels: FE

#151 Hotfix/빌드된 NestJS docker에서 JWT_SECRET 환경 변수를 읽지 못하는 문제 수정
  docker-compose.yml
Labels: Bug, Build, P1

#153 Hotfix/certbot 인증서 관련 경로 수정 및 SSL 인증서 발급 완료
  docker-compose.yml
Labels: Bug, P1

#154 Feature/#149 Swagger API 문서 구축
  pnpm-lock.yaml
  server/package.json
  server/src/app.controller.ts
  server/src/auth/auth.controller.ts
  server/src/auth/dto/user.dto.ts
  server/src/main.ts
  server/src/swagger/swagger.config.ts
Labels: Docs, BE

#152 Feature/#109 crdt 클라이언트 서버 연동
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  client/src/apis/useSocket.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.service.ts
Labels: FE, BE, Feat

#160 Feature/#140 로그인 회원가입 api 연결
  client/src/App.tsx
  client/src/apis/auth.ts
  client/src/apis/axios.ts
  client/src/components/modal/modal.style.ts
  client/src/components/sidebar/MenuButton.style.ts
  client/src/components/sidebar/MenuButton.tsx
  client/src/components/sidebar/Sidebar.style.ts
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/auth/AuthButton.tsx
  client/src/features/auth/AuthModal.tsx
  client/src/features/editor/Editor.tsx
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/components/IntroScreen.style.ts
  client/src/main.tsx
  client/src/stores/useErrorStore.ts
  client/src/stores/useUserStore.ts
  client/tsconfig.json
  client/tsconfig.tsbuildinfo
  pnpm-lock.yaml
  server/jest.config.ts
  server/package.json
  server/src/@types/express/index.d.ts
  server/src/app.module.spec.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.interface.ts
  server/src/auth/auth.module.spec.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/user.dto.ts
  server/src/auth/guards/jwt-auth.guard.ts
  server/src/auth/guards/jwt-refresh-token-auth.guard.ts
  server/src/auth/jwt-auth.guard.ts
  server/src/auth/jwt.strategy.ts
  server/src/auth/schemas/user.schema.ts
  server/src/auth/strategies/jwt-refresh-token.strategy.ts
  server/src/auth/strategies/jwt.strategy.ts
  server/src/auth/test/auth.controller.spec.ts
  server/src/auth/test/auth.module.spec.ts
  server/src/auth/test/auth.service.spec.ts
  server/src/main.ts
  server/src/swagger/swagger.config.ts
Labels: FE, BE, Feat

#161 Feature/#159 블록 애니메이션 구현
  client/src/features/editor/Editor.style.ts
  client/src/features/editor/components/block/Block.animation.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockAnimtaion.ts
Labels: FE, Feat

#165 Feature/#164 배포 환경 변수 설정
  .github/workflows/deploy.yml
  .github/workflows/lint_and_test.yml
  .github/workflows/lint_and_unit_test.yml
  docker-compose.yml
Labels: Build

#163 Feature/#156 server에 Page별 editor crdt 적용
  .gitignore
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/LinkedList.ts
  @noctaCrdt/Node.ts
  @noctaCrdt/NodeId.ts
  @noctaCrdt/Page.ts
  @noctaCrdt/WorkSpace.ts
  client/src/App.tsx
  client/src/apis/useSocket.ts
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/sidebar/PageItem.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/page/Page.tsx
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/features/workSpace/hooks/useWorkspaceInit.ts
  client/src/stores/useSocketStore.ts
  client/src/types/page.ts
  client/tsconfig.tsbuildinfo
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.module.ts
  server/src/crdt/crdt.service.ts
  server/src/crdt/schemas/document.schema.ts
  server/src/crdt/schemas/workspace.schema.ts
Labels: FE, BE, Feat, P1

#169 Feature/#168 블록 드래그앤드랍 서버 반영
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/hooks/useBlockDragAndDrop.ts
  client/src/stores/useSocketStore.ts
  server/src/crdt/crdt.gateway.ts
Labels: FE, Feat, P1

#177 Feature/#042 블록에 마우스를 호버하면 한 쪽 끝에 옵션 버튼 구현
  client/src/features/editor/components/MenuBlock/MenuBlock.style.ts
  client/src/features/editor/components/MenuBlock/MenuBlock.tsx
  client/src/features/editor/components/block/Block.style.ts
Labels: FE, Design

#172 Feature/#171 한글 crdt 연동되도록 구현
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useMarkdownGrammer.ts
Labels: FE, Feat

#179 Feature/#178 페이지 리사이징 기능 확장
  client/src/features/page/Page.style.ts
  client/src/features/page/Page.tsx
  client/src/features/page/hooks/usePage.ts
Labels: FE, Feat

#176 Feature/#175 캐럿 관리방식 변경
  @noctaCrdt/Crdt.ts
  @noctaCrdt/LinkedList.ts
  client/src/App.tsx
  client/src/constants/option.ts
  client/src/features/editor/Editor.style.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockDragAndDrop.ts
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/utils/caretUtils.ts
Labels: Bug, FE, Feat

#190 Feature/#189 accessToken도 세션스토리지에 저장
  client/src/App.tsx
  client/src/stores/useUserStore.ts
Labels: FE, Feat

#185 Feature/#184 페이지 삭제 구현
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/WorkSpace.ts
  client/src/components/sidebar/PageItem.style.ts
  client/src/components/sidebar/PageItem.tsx
  client/src/components/sidebar/Sidebar.style.ts
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/editor/Editor.style.ts
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/stores/useSocketStore.ts
  server/src/crdt/crdt.gateway.ts
Labels: FE, BE, Feat

#188 Feature/#180 리치 텍스트 구현
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/LinkedList.ts
  @noctaCrdt/Node.ts
  client/package.json
  client/src/constants/color.ts
  client/src/constants/option.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
  client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.tsx
  client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
  client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.tsx
  client/src/features/editor/components/TextOptionModal/TextOptionModal.style.ts
  client/src/features/editor/components/TextOptionModal/TextOptionModal.tsx
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/editor/hooks/useTextOptions.ts
  client/src/features/editor/utils/domSyncUtils.ts
  client/src/stores/useSocketStore.ts
  client/src/styles/tokens/color.ts
  client/src/styles/typography.ts
  client/src/utils/caretUtils.ts
  pnpm-lock.yaml
  server/src/crdt/crdt.gateway.ts
Labels: FE, Feat, P1

#191 Feature/#183 게스트, 유저별 workspace를 생성하고 불러오기
  @noctaCrdt/Crdt.ts
  client/src/App.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/editor/Editor.tsx
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/page/Page.tsx
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/stores/useSocketStore.ts
  client/src/types/page.ts
  client/src/utils/caretUtils.ts
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.module.ts
  server/src/crdt/crdt.service.ts
Labels: FE, BE

#194 Feature/#193 한글 캐럿 계속 업데이트 되는 문제 수정
  client/src/features/editor/Editor.tsx
  client/src/features/page/Page.tsx
  client/src/features/workSpace/WorkSpace.tsx
Labels: Bug, FE

#197 Feature/#110 crdt mongo db 연동
  client/tsconfig.tsbuildinfo
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.service.ts
  server/src/crdt/schemas/workspace.schema.ts
Labels: BE

#199 Feature/#195 페이지 아이콘 수정
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/Page.ts
  client/package.json
  client/src/components/button/IconButton.tsx
  client/src/components/sidebar/PageItem.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/sidebar/components/menuButton/MenuButton.style.ts
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
  client/src/components/sidebar/components/pageIconButton/PageIconButton.style.ts
  client/src/components/sidebar/components/pageIconButton/PageIconButton.tsx
  client/src/components/sidebar/components/pageIconButton/PageIconModal.tsx
  client/src/components/sidebar/components/pageIconButton/pageIconModal.style.ts
  client/src/components/sidebar/components/pageItem/PageItem.style.ts
  client/src/components/sidebar/components/pageItem/PageItem.tsx
  client/src/constants/PageIconButton.config.ts
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/types/page.ts
  pnpm-lock.yaml
  server/src/crdt/crdt.gateway.ts
Labels: FE, Design, Feat

#203 Feature/#196 페이지 title 서버인스턴스에 저장
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/WorkSpace.ts
  client/src/features/editor/Editor.tsx
  client/src/features/page/Page.tsx
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/stores/useSocketStore.ts
  client/tsconfig.tsbuildinfo
  server/src/crdt/crdt.gateway.ts
Labels: FE, BE, Feat

#207 Feature/#17 수평선 구현
  @noctaCrdt/Interfaces.ts
  client/src/features/editor/Editor.style.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
Labels: FE, Feat

#208 Feature/#201 자동완성 기본 ui 제거
  client/src/features/auth/AuthModal.style.ts
  client/src/features/auth/AuthModal.tsx
  client/src/styles/global.ts
Labels: FE, Feat

#209 Feature/#206 이전 텍스트 스타일 연속으로 적용
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/TextOptionModal/TextOptionModal.tsx
Labels: Bug, FE, Design

#210 Feature/#39 슬래시를 입력하여 블록 생성 목록 구현
  client/src/constants/option.ts
  client/src/features/editor/components/OptionModal/OptionModal.style.ts
  client/src/features/editor/components/TypeOptionModal/TypeOptionModal.tsx
  client/src/features/editor/components/block/Block.tsx
Labels: FE, Feat

#212 Feature/#198 하위 요소까지 복제 삭제 기능 구현
  client/src/features/editor/hooks/useBlockOption.ts
Labels: FE, Feat

#214 Feature/#011 순서있는 리스트 숫자 구현
  @noctaCrdt/Crdt.ts
  @noctaCrdt/LinkedList.ts
  @noctaCrdt/Node.ts
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
Labels: FE, Feat, P1

#221 Hotfix/#220 특수문자 있는 경우에도 텍스트 드래그 되도록 수정
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/utils/domSyncUtils.ts
Labels: Bug, FE, P1

#223 Hotfix/#222 드래그하고 입력할때 텍스트 안지워지는 문제 해결
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockOperation.ts
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useCopyAndPaste.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
Labels: Bug, FE, P1

#225 Feature/#218 인트로 스크린 로티애니메이션 및 pretendard 폰트적용
  client/index.html
  client/panda.config.ts
  client/src/assets/fonts/Pretendard-Bold.woff
  client/src/assets/fonts/Pretendard-Bold.woff2
  client/src/assets/fonts/Pretendard-Medium.woff
  client/src/assets/fonts/Pretendard-Medium.woff2
  client/src/assets/icons/noctaDayIcon.svg
  client/src/assets/icons/noctaNightIcon.svg
  client/src/assets/lotties/noctaDayIcon.json
  client/src/assets/lotties/noctaNightIcon.json
  client/src/components/lotties/NoctaIcon.tsx
  client/src/components/sidebar/components/menuButton/MenuButton.style.ts
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
  client/src/components/sidebar/components/menuButton/components/MenuIcon.style.ts
  client/src/components/sidebar/components/menuButton/components/MenuIcon.tsx
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/components/IntroScreen.animation.ts
  client/src/features/workSpace/components/IntroScreen.style.ts
  client/src/features/workSpace/components/IntroScreen.tsx
  client/src/features/workSpace/hooks/useWorkspaceInit.ts
  client/src/styles/global.ts
  client/src/styles/typography.ts
Labels: FE, Design

#227 Feature/#215 CRDT 통신 로직 최적화
  @noctaCrdt/Crdt.ts
  @noctaCrdt/Interfaces.ts
  client/src/apis/useSocket.ts
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/editor/Editor.style.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/TypeOptionModal/TypeOptionModal.tsx
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockOperation.ts
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useCopyAndPaste.ts
  client/src/features/editor/hooks/useEditorOperation.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/editor/hooks/useTextOptions.ts
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/stores/useSocketStore.ts
  client/src/utils/caretUtils.ts
  client/tsconfig.tsbuildinfo
  docker-compose.yml
  server/src/crdt/crdt.gateway.ts
  server/src/crdt/crdt.service.ts
Labels: Refactor, BE

#229 Hotfix/NginX 빌드 권한 수정
  docker-compose.yml
Labels: Bug, P1

#230 Hotfix/빌드 권한 설정 롤백
  docker-compose.yml
Labels: Bug, P1

#226 Feature/#213 하위요소 블록 드래그앤드랍 구현
  @noctaCrdt/LinkedList.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/IconBlock/IconBlock.style.ts
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  client/src/features/editor/components/block/Block.style.ts
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockDragAndDrop.ts
  client/src/features/editor/hooks/useEditorOperation.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
Labels: FE, Feat

#235 Feature/#234 페이지 삭제시, 삭제 토글창 알림
  @noctaCrdt/Interfaces.ts
  client/src/components/Toast/Toast.style.ts
  client/src/components/Toast/Toast.tsx
  client/src/components/Toast/ToastContainer.style.ts
  client/src/components/Toast/ToastContainer.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/sidebar/components/pageItem/PageItem.tsx
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/stores/useToastStore.ts
  client/src/types/toast.ts
  server/src/crdt/crdt.gateway.ts
Labels: FE, BE

#232 Feature/#231_remote페이지_제목_반영_안되는_버그 및 아이콘 반영 버그 수정
  client/src/components/sidebar/components/pageItem/PageItem.tsx
  client/src/features/editor/Editor.tsx
Labels: Bug, P1

#237 Feature/#236 문제상황에 대해 isComposing 일 경우 이벤트 막도록
  client/src/features/editor/hooks/useMarkdownGrammer.ts
Labels: Bug, FE

#243 Hotfix/#242 마크다운 탐지 로직 수정
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/editor/utils/domSyncUtils.ts
Labels: Bug, FE, P1

#241 Feature/#239 esc를 누르거나, 옵션창 외부 클릭시 옵션창 사라지도록 구현
  client/src/features/editor/components/TypeOptionModal/TypeOptionModal.tsx
Labels: FE, Feat

#244 Hotfix: sanitize 롤백
  client/src/features/editor/utils/domSyncUtils.ts
Labels: Bug, FE, P1

#247 Feature/#246_스타일 개선
  client/src/components/modal/modal.tsx
  client/src/constants/color.ts
  client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
  client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
  client/src/features/page/components/PageTitle/PageTitle.style.ts
  client/src/features/page/components/PageTitle/PageTitle.tsx
Labels: Bug, Design
