Repository boostcampwm-2024/web33-Nocta, pull requests merged in 2024-12, with the labels that each got.

#254 Feature/#253 온보딩 오버레이 추가
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/button/textButton.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
  client/src/features/auth/AuthButton.tsx
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/components/OnboardingOverlay.style.ts
  client/src/features/workSpace/components/OnboardingOverlay.tsx
Labels: FE

#250 Feature/#71 로그인한 사용자는 권한이 있는 워크스페이스에 다른 사용자를 초대 구현
  @noctaCrdt/Interfaces.ts
  client/src/App.tsx
  client/src/components/modal/InviteModal.style.ts
  client/src/components/modal/InviteModal.tsx
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
  client/src/components/sidebar/components/menuButton/components/WorkspaceSelectModal.style.ts
  client/src/components/sidebar/components/menuButton/components/WorkspaceSelectModal.tsx
  client/src/components/sidebar/components/menuButton/components/components/InviteButton.style.ts
  client/src/components/sidebar/components/menuButton/components/components/InviteButton.tsx
  client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.style.tsx
  client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.tsx
  client/src/stores/useSocketStore.ts
  server/src/auth/auth.service.ts
  server/src/workspace/workspace.gateway.ts
  server/src/workspace/workspace.interface.ts
  server/src/workspace/workspace.service.ts
Labels: FE, BE, Feat, P2

#251 Feature/#240 페이지 반응형 구현
  client/src/components/button/IconButton.style.ts
  client/src/components/button/textButton.style.ts
  client/src/components/sidebar/Sidebar.style.ts
  client/src/features/auth/AuthButton.style.ts
  client/src/features/auth/AuthButton.tsx
  client/src/features/page/Page.tsx
  client/src/features/page/components/PageControlButton/PageControlButton.style.ts
  client/src/features/page/components/PageControlButton/PageControlButton.tsx
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/WorkSpace.style.ts
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/styles/global.ts
Labels: FE, Feat

#257 Hotfix/Conflict_과정중_JSX문법_에러
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
Labels: Bug

#258 Hotfix/#252 블록에 한글 첫입력시 캐럿 튀는문제
  client/src/features/editor/Editor.tsx
  client/src/features/editor/hooks/useBlockOperation.ts
Labels: Bug, FE, P1

#259 Hotfix/console.log 제거
  client/src/App.tsx
  client/src/features/editor/hooks/useEditorOperation.ts
  client/src/features/workSpace/components/OnboardingOverlay.tsx
  server/src/workspace/workspace.gateway.ts
Labels: FE, P1

#268 Feature/#267 이미지 최적화
  client/src/assets/images/background.avif
  client/src/assets/images/background.webp
  client/src/styles/global.ts
Labels: FE, Feat

#272 Feature/#271 seo 최적화
  client/index.html
  client/public/images/nocta.png
  client/public/robots.txt
  client/public/sitemap.xml
  client/vite.config.ts
  nginx/default.conf
  nginx/default.dev.conf
  pnpm-lock.yaml
Labels: FE, BE, Feat

#273 Feature/#269 workspace 관련 완성도 개선
  client/src/assets/icons/pencil.svg
  client/src/components/modal/RenameModal.style.ts
  client/src/components/modal/RenameModal.tsx
  client/src/components/sidebar/components/menuButton/MenuButton.style.ts
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
  client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.style.tsx
  client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.tsx
  client/src/features/workSpace/components/OnboardingOverlay.style.ts
  client/src/features/workSpace/components/OnboardingOverlay.tsx
  client/src/stores/useSocketStore.ts
  client/src/stores/useWorkspaceStore.ts
  server/src/workspace/workspace.gateway.ts
  server/src/workspace/workspace.service.ts
Labels: FE, BE, Feat, P2

#274 Feature/#270 체크박스 기능 추가
  @noctaCrdt/Interfaces.ts
  @noctaCrdt/Node.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/IconBlock/IconBlock.style.ts
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockOperation.ts
  client/src/features/editor/hooks/useEditorOperation.ts
  client/src/stores/useSocketStore.ts
  server/src/workspace/workspace.gateway.ts
Labels: FE, Feat

#277 Feature/#276 순서리스트 null나오는 현상
  server/src/workspace/workspace.gateway.ts
Labels: BE

#280 Hotfix/#278 캐럿이 계속 튀는 문제
  client/src/features/editor/Editor.tsx
Labels: FE, Feat

#283 Feature/#279 회원가입 유효성 검사 구현
  client/src/apis/auth.ts
  client/src/components/inputField/InputField.style.ts
  client/src/components/inputField/InputField.tsx
  client/src/features/auth/AuthButton.tsx
  client/src/features/auth/AuthModal.style.ts
  client/src/features/auth/AuthModal.tsx
Labels: FE, Design, Feat, P1

#284 Feature/#275 흰색으로 바꾸고 그림자 효과를주어 흰색이 표시되게 변경
  client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
  client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
Labels: Design

#287 Feature/backspace눌렀을때 캐럿 튀는 문제
  client/src/features/editor/Editor.tsx
Labels: FE, Refactor

#286 Hotfix/#286 스타일 적용된 텍스트 이어서 작성할 때 서버 반영 안되는 문제 해결
  @noctaCrdt/Crdt.ts
  client/src/features/editor/hooks/useBlockOperation.ts
Labels: Bug, FE, P1

#289 Hotfix/#288 스타일 적용된 태그에 스페이스만 남아있을 때 에러나는 문제
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/utils/domSyncUtils.ts
Labels: Bug, FE, P1

#291 Hotfix/#288 다른 블록에서 캐럿 튀는 문제, 배치 처리 다시 추가
  client/src/features/editor/utils/domSyncUtils.ts
  client/src/stores/useSocketStore.ts
Labels: Bug, FE

#292 Feature/#290 icon block 맨위에 위치하도록 수정
  client/index.html
  client/src/features/editor/components/IconBlock/IconBlock.style.ts
  client/src/features/editor/components/MenuBlock/MenuBlock.style.ts
  client/src/features/editor/components/block/Block.style.ts
Labels: FE, Refactor

#296 Feature/#282 인터랙티브 컴포넌트 추가
  @noctaCrdt/Interfaces.ts
  client/src/constants/option.ts
  client/src/features/editor/components/block/Block.animation.ts
Labels: FE, Feat

#294 Feature/#293 Access Token 인증 과정에서 tokenVersion 제거
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/guards/jwt-auth.guard.ts
  server/src/auth/schemas/user.schema.ts
  server/src/auth/test/auth.controller.spec.ts
  server/src/auth/test/auth.service.spec.ts
Labels: BE

#297 Feature/#295 db에 문서가 저장되지 않는 문제 수정
  server/src/workspace/schemas/workspace.schema.ts
  server/src/workspace/workspace.gateway.ts
  server/src/workspace/workspace.service.ts
Labels: BE, P1

#300 Hotfix/#299 붙여넣기 할 때 순서 리스트 유지되도록 수정
  client/src/features/editor/hooks/useCopyAndPaste.ts
Labels: Bug, FE, P1

#301 Feature/#267 이미지 최적화
  client/src/App.tsx
  client/src/components/backgroundImage/BackgroundImage.tsx
  client/src/styles/global.ts
Labels: FE

#302 Feature/#255 페이지 선택할때 화면 벗어나가지 않도록 수정
  client/src/components/sidebar/components/menuButton/MenuButton.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
Labels: FE, Feat

#305 Feature/#303 사용하지 않는 position 변수 제거
  client/src/features/editor/hooks/useEditorOperation.ts
Labels: FE, Refactor

#307 Feature/#306 leave/page 누락건 추가
  client/src/features/workSpace/hooks/usePagesManage.ts
Labels: Bug, FE, P1

#309 Hotfix/#308 마크다운 문법 붙여넣기 수정
  client/src/features/editor/hooks/useCopyAndPaste.ts
Labels: Bug, FE, Feat

#310 Hotfix/블록 전환시 순서 리스트 유지
  client/src/features/editor/hooks/useBlockOption.ts
Labels: Bug, FE
